-- AlterTable
ALTER TABLE "Hoodies" ALTER COLUMN "size" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Shorts" ALTER COLUMN "size" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "T_Shirt" ALTER COLUMN "size" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Trousers" ALTER COLUMN "size" SET DATA TYPE TEXT;
